export enum FaultType {
    HIGH_ENGINE_TEMPERATURE = "HIGH_ENGINE_TEMPERATURE",
    LOW_OIL_PRESSURE = "LOW_OIL_PRESSURE",
    LOW_FUEL_LEVEL = "LOW_FUEL_LEVEL",
    HIGH_GENERATOR_CURRENT = "HIGH_GENERATOR_CURRENT",
    LOW_BATTERY = "LOW_BATTERY",
    COOLING_FAILURE = "COOLING_FAILURE"
}
